language: go
go:
  - 1.5.3

script:
  - go test -v ./...
before_deploy:
  - go get github.com/inconshreveable/mousetrap # temporary fix for travis build breaks for windows due to cobra dependency on mousetrap
  - GOOS=darwin GOARCH=amd64 go build -o b4a -v github.com/back4app/parse-cli
  - GOOS=windows GOARCH=386 go build -o b4a.exe -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=386 go build -o b4a_linux -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=arm go build -o b4a_linux_arm -v github.com/back4app/parse-cli
deploy:
  provider: releases
  api_key:
    secure: "sbeMlr9kdF3idQtd0f1JgES9j1CvoZqx+u5Ah5S9OOlKbn5VdeitVCkDo16jFhHrjG/Ic1Al3m8W/2+HUNLFgS3QV2MGcPtk8Csj973Oh1ro4OJlp5mierdaDTeP7FMqLhMq1uLq6oYv+sMnsmOROmPi/DeYDXhfp0MfB8m7Dfr5/i9Rpi5u3Udv30wK67Ua/BrNrk+Fyiot2p8CIRmhD5MovhBxpHsgmDzUhRKFwMcJLirdMJEMu4B3t6dGebQf2hWqh3G8xv/lvmZBYpXXlvEwCBcsZeOzgeWTlPS0vUxHSCpW1KA/BpH7eIu5pXPAgt0ri316c3zywPND8wOA88j+ugm4hw5c8ls8BpyF89oqBBcuc5hqu3Ljglv5cY6w4DMqvyUSWGAQgtZZ/T8tZtz3LbC4Wpbd1ibor5++MtxaGEQZyncSGL5c2Pi4aP/gTduEz55dsNXDapWAKuw0UkXw6cOwnGcsHbyK2iim33r821tXN+Q5eU5d4zN0vZs66bVrUkZcHAbe05/xinrBO28KBe8Ifmx3/yDOh1+3eRSgnva/g87mrgGDJ5ndV/gLdBUzq8fcCCKMQ+XrXvpdIxJ4Cqlg3E3PPGUKBXIw73UhgXlVOAdIny9aBHe7RAwLmSCGlfiq+HGUcYUZQ0lLUxHeE6v1EraCZ1WkH1SMg34="

  file:
    - b4a
    - b4a.exe
    - b4a_linux
    - b4a_linux_arm
  skip_cleanup: true
  on:
    repo: back4app/parse-cli
    tags: true
    condition: $TRAVIS_TAG =~ ^release_.*
